# .github/workflows/main.yml

name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: denoland/setup-deno@v1
      - uses: actions/checkout@v2
      - name: Build
        run: |
          deno install -A -f -n land https://deno.land/x/land@v0.7.0/cli.ts
          land aleph@0.3.0-beta.19 build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist